# Generated by Django 5.2.16 on 2026-07-28 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('CNIC', 'CNIC'), ('PASSPORT', 'Passport'), ('DEGREE', 'Degree'), ('EXPERIENCE_LETTER', 'Experience Letter')], max_length=30)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeemodel')),
            ],
        ),
    ]
