# Generated by Django 5.2.16 on 2026-08-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesmodel',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
        migrations.AlterField(
            model_name='leavesmodel',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('ANNUAL', 'Annual Leave')], max_length=50),
        ),
    ]
