# Generated by Django 5.2.16 on 2026-08-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leaves', '0002_leavesmodel_medical_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_allowed', models.PositiveIntegerField(default=12)),
                ('casual_used', models.PositiveIntegerField(default=0)),
                ('casual_remaining', models.PositiveIntegerField(default=12)),
                ('sick_allowed', models.PositiveIntegerField(default=12)),
                ('sick_used', models.PositiveIntegerField(default=0)),
                ('sick_remaining', models.PositiveIntegerField(default=12)),
                ('anual_allowed', models.PositiveIntegerField(default=12)),
                ('anual_used', models.PositiveIntegerField(default=0)),
                ('anual_remaining', models.PositiveIntegerField(default=12)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employeemodel')),
            ],
        ),
    ]
