# Generated by Django 5.2.16 on 2026-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
